Repository opensource-observer/oss-directory, pull requests merged in 2024-06, with the labels that each got.

#324 Update passportxyz.yaml
  data/projects/p/passportxyz.yaml
Labels: pr:waiting_for_merge_review

#338 Update 0xSplits entry with new data
  data/projects/0/0x-splits.yaml
Labels: pr:waiting_for_merge_review

#333 Update Compound.finance on Optimism
  data/projects/c/compound-finance.yaml
Labels: pr:waiting_for_merge_review

#310 add: offline_oracles
  data/projects/o/offline-oracles.yaml
Labels: pr:waiting_for_merge_review

#331 add zerodev kernel contract (using OP address we use)
  data/projects/z/zerodev.yaml
Labels: pr:waiting_for_merge_review

#308 Update superfluid.yaml
  data/projects/s/superfluid.yaml
Labels: pr:waiting_for_merge_review

#332 Add CMT
  data/projects/c/createmytoken.yaml
Labels: pr:critical_issue

#342 Add ACI deployers to aave addresses list
  data/projects/a/aave.yaml
Labels: pr:waiting_for_merge_review

#337 add: velodrome, aerodrome contracts
  data/projects/a/aerodrome-finance.yaml
  data/projects/v/velodrome.yaml
Labels: pr:changes_suggested

#344 Socket details fix
  data/projects/s/socket-tech.yaml
  data/projects/s/socket.yaml
Labels: pr:critical_issue

#351 Add EntryPoint v0.7 and mark the version for EntryPoint v0.6
  data/projects/e/eth-infinitism-account-abstraction.yaml
Labels: pr:changes_suggested

#325 Add All HypoDrop Projects
  data/projects/h/hypodropcom.yaml
  package-lock.json
Labels: pr:changes_suggested

#349 Create castnotes.yaml
  data/projects/c/castnotes.yaml
Labels: pr:changes_suggested

#328 Add zkcodex.yaml
  data/projects/z/zkcodex.yaml
Labels: pr:critical_issue

#356 Add axelarnetwork
  data/projects/a/axelar.yaml
Labels: pr:changes_suggested

#357 Add NOGS
  data/projects/n/nnsprotocol.yaml
Labels: pr:changes_suggested

#363 Update paraswap.yaml: Adding Base
  data/projects/p/paraswap.yaml
Labels: pr:changes_suggested

#374 Create apriloracle.yaml
  data/projects/a/apriloracle.yaml
Labels: pr:changes_suggested

#362 Add Drawtech to OSS
  data/projects/s/smallbraingames.yaml
Labels: pr:critical_issue

#370 Create anyinu.yaml
  data/projects/a/anyinu.yaml
Labels: pr:changes_suggested
